.github/workflows/publish.yml

update github action

---

docusaurus.config.js
src/components/HomepageFeatures.js
src/css/custom.css

[https://github.com/harvester/harvester/issues/853](https://github.com/harvester/harvester/issues/853)

polish font size on mobile

---

docusaurus.config.js

- add version selection button.
- add 0.2.0 drop-down button.
- ~add example code for future 0.x.x drop-down buttons.~

add version selection button

---

config.toml
content/_index.html

Update doc link

---

assets/sass/main.scss
content/_index.html

[https://github.com/harvester/harvester/issues/853](https://github.com/harvester/harvester/issues/853)

[Branch main]Polish on mobile

---

content/_index.html

Update video link

---

kb/2022-03-07/vm-scheduling.md

Related issue: https://github.com/harvester/harvester/issues/1654

Add KB - VM Scheduling in Harvester

---

docusaurus.config.js

The first KB article has been published, so we can enable the link now

Enabled Knowledge Base link

---

kb/2022-03-10/multiple_nics_vm_connectivity.md

related to https://github.com/harvester/harvester/issues/1059
Signed-off-by: Date Huang <date.huang@suse.com>

KB: add multiple NICs issue

---

docusaurus.config.js

Adding GA plugin that was missed during refactor

Adding Google Analytics Plugin

---

src/components/HomepageFeatures.js

Finally found the file to edit - correcting Kubevirt to KubeVirt

Fix typo in HomepageFeatures.js

---

kb/2023-01-12/evict_replicas_from_a_disk.md

Related issue: https://github.com/harvester/harvester/issues/3364
Add a KB article for doing this with CLI.
The formal doc to remove a disk (GUI way) will be addressed in https://github.com/harvester/harvester/issues/3345.

Add evicting disk KB (The CLI way)

---

kb/2023-07-06/package_your_own_toolbox_image.md

- we provide the example for users building their toolbox image
related issue: https://github.com/harvester/harvester/issues/2391

KB: add HowTo package the toolbox image

---

kb/2023-07-25/configure_priority_class_longhorn.md

Add KB to help users who upgrade from previous versions.
Related issue: https://github.com/harvester/harvester/issues/3756
Preview: https://deploy-preview-37--harvester-home-preview.netlify.app/kb/configure_priority_class_longhorn

KB: set priority class for Longhorn system-managed components

---

docusaurus.config.js

Display all posts in the kb sidebar

---

kb/2023-08-11/using_netapp_third_party_storage.md

Add knowledge base article describing how to install the NetApp Astra Trident CSI driver to enable use of NetApp storage systems for Harvester volume storage.

KB article for NetApp Trident CSI Driver

---

src/components/HomepageFeatures.js

update the link for Harvester Global Meetup 2023

update the link for Harvester Global Meetup 2023

---

docusaurus.config.js

put back blog and kb

---

kb/2023-09-01/vm_live_migration_policy_and_configuration.md

Add kb of vm live migration policy and configuration
Signed-off-by: Jian Wang <w13915984028@gmail.com>
issue:
https://github.com/harvester/harvester/issues/4376

Add kb of vm live migration policy and configuration

---

kb/2024-03-05/booting_harvester_via_iscsi_ibt.md

redo of previous pull request because the previous repo got messed up and github wouldn't let me merge it even after approval.
This single commit should match the final version from the previously approved PR https://github.com/harvester/harvesterhci.io/pull/57

Add article describing how to have Harvester boot from iSCSI using a converged network adapter

---

kb/2023-12-27/best_practices_disk_performance.md

Related issue: [#563](https://github.com/harvester/docs/issues/563)

Replace doc links in Longhorn best practices KB

---

.github/workflows/deploy.yml

feat: use GHA to deploy pages

---

kb/2025-03-14/iso_boot_fails_with_sbat_error.md

Related issue: https://github.com/harvester/harvester/issues/7343

kb: add "Harvester ISO boot fails with SBAT error"

---

kb/2025-03-25/cve-2025-1974.md

Add mitigation steps for ingress-nginx vulnerability (CVE-2025-1974).
Issue: https://github.com/harvester/harvester/issues/7941

kb: (cve-2025-1974) add mitigation steps for ingress-nginx vulnerability

---

kb/2025-05-08/using-pod-security-standard.md

KB article detailing limitations of using PSS with Harvester and how to use baseline PSS with Harvester
https://github.com/harvester/harvester/issues/8223

kb on leverage PSS with Harvester baremetal workloads
